---
models.app:
  ycappuccino-permissions: true
  ycappuccino-remote_storage: true

layers:
  ycappuccino-permissions:
    active: true
  ycappuccino-remote:
    active: true
    host: localhost
    port: 0
    scheme: http
name: scheduler
bundle_prefix: ycappuccino
