---
models.app:
  ycappuccino_permissions: true
  ycappuccino_service_comm_storage: true

layers:
  ycappuccino_permissions:
    active: true
  ycappuccino_service_comm:
    active: true
    host: localhost
    port: 0
    scheme: http
name: scheduler
bundle_prefix: ycappuccino
